name: Lean Action CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: |
          sudo apt-get install macaulay2
      - uses: actions/checkout@v4
      - uses: leanprover/lean-action@v1
